# Generated by Django 4.1.2 on 2022-11-25 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skul', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
