# Generated by Django 4.1.2 on 2022-11-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skul', '0002_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu',
            name='password',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
