# Generated by Django 4.1.2 on 2022-11-29 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skul', '0004_stu_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stu',
            name='user',
        ),
    ]
